[2021-12-08 08:57:10,265: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-12-08 08:57:12,274: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-12-08 08:57:16,291: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq-service:5672//
[2021-12-08 08:57:16,308: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 08:57:17,306: INFO/MainProcess] mingle: all alone
[2021-12-08 08:57:17,340: INFO/MainProcess] celery@8566fcab9de3 ready.
[2021-12-08 08:58:58,931: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-12-08 08:59:00,942: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-12-08 08:59:04,953: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-12-08 08:59:10,976: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq-service:5672//
[2021-12-08 08:59:10,999: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 08:59:12,051: INFO/MainProcess] mingle: all alone
[2021-12-08 08:59:12,080: INFO/MainProcess] celery@f3f2f75ea6c1 ready.
[2021-12-08 09:06:51,122: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-12-08 09:06:53,132: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-12-08 09:06:57,144: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-12-08 09:07:03,161: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq-service:5672//
[2021-12-08 09:07:03,177: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 09:07:04,219: INFO/MainProcess] mingle: all alone
[2021-12-08 09:07:04,250: INFO/MainProcess] celery@52ae07abfad1 ready.
[2021-12-08 09:16:05,448: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-12-08 09:16:07,459: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-12-08 09:16:11,477: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-12-08 09:16:46,945: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-12-08 09:16:48,956: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-12-08 09:16:52,966: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-12-08 09:16:58,992: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq-service:5672//
[2021-12-08 09:16:59,013: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 09:17:00,066: INFO/MainProcess] mingle: all alone
[2021-12-08 09:17:00,095: INFO/MainProcess] celery@eb566fa3ae91 ready.
[2021-12-08 09:18:07,404: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-12-08 09:18:09,414: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-12-08 09:18:13,431: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq-service:5672//
[2021-12-08 09:18:13,454: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 09:18:14,492: INFO/MainProcess] mingle: all alone
[2021-12-08 09:18:14,517: INFO/MainProcess] celery@612ffd72f2b6 ready.
[2021-12-08 09:20:21,753: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-12-08 09:20:23,760: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-12-08 09:20:27,775: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-service:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-12-08 09:20:33,799: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq-service:5672//
[2021-12-08 09:20:33,814: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 09:20:34,853: INFO/MainProcess] mingle: all alone
[2021-12-08 09:20:34,895: INFO/MainProcess] celery@30e89bc6dfc5 ready.
[2021-12-08 09:20:38,743: INFO/MainProcess] Task x-ml.test[a8feab9b-4917-4256-405f-9d09607be82f] received
[2021-12-08 09:20:38,749: WARNING/ForkPoolWorker-1] test
[2021-12-08 09:20:38,753: WARNING/ForkPoolWorker-1] 

[2021-12-08 09:20:38,764: INFO/ForkPoolWorker-1] Task x-ml.test[a8feab9b-4917-4256-405f-9d09607be82f] succeeded in 0.01576760000170907s: None
